language: python

before_install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip -nv
  - unzip -q google_appengine_1.9.17.zip

script:
  - make runtests GAE=./google_appengine
