# Demo app.
# "application:" and "version:" need to be specified from CLI
runtime: python27
api_version: 1
threadsafe: True

handlers:

- url: /django_middleware
  script: django_middleware_test.app

- url: /fibo.*
  script: fibo.app

- url: /intest.*
  script: intest.app

- url: /hello.*
  script: hello.app

- url: /home
  script: main.app

- url: /account
  script: main.app

- url: /dataviewer.*
  script: dataviewer.app

- url: /.*
  script: guestbook.application

builtins:
- appstats: on
- remote_api: on
